#define TOKEN_TEST_AND                         1
#define TOKEN_TEST_OR                          2
#define TOKEN_TEST_EQ                          3
#define TOKEN_TEST_NE                          4
#define TOKEN_TEST_LT                          5
#define TOKEN_TEST_LE                          6
#define TOKEN_TEST_GT                          7
#define TOKEN_TEST_GE                          8
#define TOKEN_TEST_CONTAINS                    9
#define TOKEN_TEST_NOT                        10
#define TOKEN_FIELD                           11
#define TOKEN_STRING                          12
#define TOKEN_UNPARSED                        13
#define TOKEN_INTEGER                         14
#define TOKEN_LPAREN                          15
#define TOKEN_RPAREN                          16
