#define TOKEN_TEST_AND                         1
#define TOKEN_TEST_OR                          2
#define TOKEN_TEST_EQ                          3
#define TOKEN_TEST_NE                          4
#define TOKEN_TEST_LT                          5
#define TOKEN_TEST_LE                          6
#define TOKEN_TEST_GT                          7
#define TOKEN_TEST_GE                          8
#define TOKEN_TEST_NOT                         9
#define TOKEN_FIELD                           10
#define TOKEN_STRING                          11
#define TOKEN_UNPARSED                        12
#define TOKEN_INTEGER                         13
#define TOKEN_LPAREN                          14
#define TOKEN_RPAREN                          15
